# Sysbuild configuration file.

# MCUboot für die Applikation aktivieren.
SB_CONFIG_BOOTLOADER_MCUBOOT=y


# STEP 2.2 - Disable the Partition Manager
#SB_CONFIG_PARTITION_MANAGER=y

# Paritionsmanager für Flash-Konfiguration
#SB_CONFIG_PARTITION_MANAGER=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/../../../mcuboot-private.pem"
